import { ClerkProvider } from "@clerk/clerk-react";
import { AppProps } from "next/dist/shared/lib/router/router";
import Head from "next/head";
import { useRouter } from "next/router";
import NextNProgress from "nextjs-progressbar";
import "../styles/globals.css";

const clerkFrontendApi = process.env.NEXT_PUBLIC_CLERK_FRONTEND_API;

const MyApp = ({ Component, pageProps }: AppProps) => {
  const router = useRouter();
  return (
    <ClerkProvider
      frontendApi={clerkFrontendApi}
      navigate={(to) => router.push(to)}
    >
      <Head>
        <title>Audible India | Free Audiobook with Trial | Audible.in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icon.jpg" />
      </Head>
      <NextNProgress height={6} color="#4338C9" />
      <Component {...pageProps} />
    </ClerkProvider>
  );
};

export default MyApp;
