import "../styles/globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/clerk-react";
import { useRouter } from "next/router";
import Head from "next/head";

const clerkFrontendApi = process.env.NEXT_PUBLIC_CLERK_FRONTEND_API;

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  return (
    <ClerkProvider
      frontendApi={clerkFrontendApi}
      navigate={(to) => router.push(to)}
    >
      <Head>
        <title>Audible India | Free Audiobook with Trial | Audible.in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icon.jpg" />
      </Head>
      <Component {...pageProps} />
    </ClerkProvider>
  );
}

export default MyApp;
