import React from "react";
import Head from "next/head";
import Header from "../components/Header";

function aboutmembership() {
  return (
    <div>
      <Head>
        <title>Audible India | Free Audiobook with Trial | Audible.in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icon.jpg" />
      </Head>

      <Header />
    </div>
  );
}

export default aboutmembership;
