import React from "react";
import { providers, signIn, getSession, csrfToken } from "next-auth/client";
import Image from "next/image";
import Head from "next/head";

export default function SignIn({ providers }) {
  return (
    <div className="mt-5">
      <Head>
        <title>Audible Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.audible.in/favicon.ico" />
      </Head>

      <Image
        width={140}
        height={54}
        objectFit="contain"
        src="https://m.media-amazon.com/images/G/31/audibleweb/arya/navigation/audible_logo._CB490888215_.svg"
      />
      <div>
        <div>
          {Object.values(providers).map((provider) => {
            return (
              <div key={provider.name}>
                <button onClick={() => signIn(provider.id)}>
                  Sign in with {provider.name}
                </button>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { req, res } = context;
  const session = await getSession({ req });

  if (session && res) {
    res.writeHead(302, {
      Location: "/",
    });
    res.end();
    return;
  }

  return {
    props: {
      providers: await providers(context),
      csrfToken: await csrfToken(context),
    },
  };
}
